
server:
  port: 9091

spring:
  application:
    name: Product service
  data:
    mongodb:
      database: shopping
      host: localhost
      port: 27017
  profiles:
    active: dev
product:
  currencies:
    -INR
    -USD
    -EUR

---
server:
  port: 9094
spring:
  config:
    activate:
      on-profile:
        -prod

